spring.application.name=civicos-api

spring.datasource.url=jdbc:postgresql://localhost:5433/civicos
spring.datasource.username=civicos
spring.datasource.password=civicos

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
